/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_AiurRequested_H_
#define	_AiurRequested_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AiurRequested */
typedef long	 AiurRequested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AiurRequested;
asn_struct_free_f AiurRequested_free;
asn_struct_print_f AiurRequested_print;
asn_constr_check_f AiurRequested_constraint;
ber_type_decoder_f AiurRequested_decode_ber;
der_type_encoder_f AiurRequested_encode_der;
xer_type_decoder_f AiurRequested_decode_xer;
xer_type_encoder_f AiurRequested_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AiurRequested_H_ */
#include <asn_internal.h>
