/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_BasicHSCSDParameters_H_
#define	_BasicHSCSDParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NumberOfChannels.h"
#include "ChannelCoding.h"
#include "NumberOfChannelsUsed.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChannelCodingAcceptableList;

/* BasicHSCSDParameters */
typedef struct BasicHSCSDParameters {
	NumberOfChannels_t	*maxNumberOfChannels	/* OPTIONAL */;
	struct ChannelCodingAcceptableList	*channelCodingAcceptableList	/* OPTIONAL */;
	ChannelCoding_t	*channelCodingUsed	/* OPTIONAL */;
	NumberOfChannelsUsed_t	*numberOfChannelsUsed	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicHSCSDParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicHSCSDParameters;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChannelCodingAcceptableList.h"

#endif	/* _BasicHSCSDParameters_H_ */
#include <asn_internal.h>
