/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "BasicHSCSDParameters.h"

static asn_TYPE_member_t asn_MBR_BasicHSCSDParameters_1[] = {
	{ ATF_POINTER, 4, offsetof(struct BasicHSCSDParameters, maxNumberOfChannels),
		(ASN_TAG_CLASS_APPLICATION | (161 << 2)),
		0,
		&asn_DEF_NumberOfChannels,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"maxNumberOfChannels"
		},
	{ ATF_POINTER, 3, offsetof(struct BasicHSCSDParameters, channelCodingAcceptableList),
		(ASN_TAG_CLASS_APPLICATION | (61 << 2)),
		0,
		&asn_DEF_ChannelCodingAcceptableList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"channelCodingAcceptableList"
		},
	{ ATF_POINTER, 2, offsetof(struct BasicHSCSDParameters, channelCodingUsed),
		(ASN_TAG_CLASS_APPLICATION | (60 << 2)),
		0,
		&asn_DEF_ChannelCoding,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"channelCodingUsed"
		},
	{ ATF_POINTER, 1, offsetof(struct BasicHSCSDParameters, numberOfChannelsUsed),
		(ASN_TAG_CLASS_APPLICATION | (252 << 2)),
		0,
		&asn_DEF_NumberOfChannelsUsed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfChannelsUsed"
		},
};
static const ber_tlv_tag_t asn_DEF_BasicHSCSDParameters_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (35 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BasicHSCSDParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (60 << 2)), 2, 0, 0 }, /* channelCodingUsed */
    { (ASN_TAG_CLASS_APPLICATION | (61 << 2)), 1, 0, 0 }, /* channelCodingAcceptableList */
    { (ASN_TAG_CLASS_APPLICATION | (161 << 2)), 0, 0, 0 }, /* maxNumberOfChannels */
    { (ASN_TAG_CLASS_APPLICATION | (252 << 2)), 3, 0, 0 } /* numberOfChannelsUsed */
};
static asn_SEQUENCE_specifics_t asn_SPC_BasicHSCSDParameters_specs_1 = {
	sizeof(struct BasicHSCSDParameters),
	offsetof(struct BasicHSCSDParameters, _asn_ctx),
	asn_MAP_BasicHSCSDParameters_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BasicHSCSDParameters = {
	"BasicHSCSDParameters",
	"BasicHSCSDParameters",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BasicHSCSDParameters_tags_1,
	sizeof(asn_DEF_BasicHSCSDParameters_tags_1)
		/sizeof(asn_DEF_BasicHSCSDParameters_tags_1[0]) - 1, /* 1 */
	asn_DEF_BasicHSCSDParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_BasicHSCSDParameters_tags_1)
		/sizeof(asn_DEF_BasicHSCSDParameters_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_BasicHSCSDParameters_1,
	4,	/* Elements count */
	&asn_SPC_BasicHSCSDParameters_specs_1	/* Additional specs */
};

