/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_CalledNumAnalysis_H_
#define	_CalledNumAnalysis_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CalledNumAnalysisCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CountryCodeList;
struct IacList;

/* CalledNumAnalysis */
typedef struct CalledNumAnalysis {
	CalledNumAnalysisCode_t	*calledNumAnalysisCode	/* OPTIONAL */;
	struct CountryCodeList	*countryCodeTable	/* OPTIONAL */;
	struct IacList	*iacTable	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CalledNumAnalysis_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CalledNumAnalysis;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CountryCodeList.h"
#include "IacList.h"

#endif	/* _CalledNumAnalysis_H_ */
#include <asn_internal.h>
