/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_CalledNumAnalysisCode_H_
#define	_CalledNumAnalysisCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Code.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CalledNumAnalysisCode */
typedef Code_t	 CalledNumAnalysisCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CalledNumAnalysisCode;
asn_struct_free_f CalledNumAnalysisCode_free;
asn_struct_print_f CalledNumAnalysisCode_print;
asn_constr_check_f CalledNumAnalysisCode_constraint;
ber_type_decoder_f CalledNumAnalysisCode_decode_ber;
der_type_encoder_f CalledNumAnalysisCode_encode_der;
xer_type_decoder_f CalledNumAnalysisCode_decode_xer;
xer_type_encoder_f CalledNumAnalysisCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CalledNumAnalysisCode_H_ */
#include <asn_internal.h>
