/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_CamelServerAddress_H_
#define	_CamelServerAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AddressStringDigits.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CamelServerAddress */
typedef AddressStringDigits_t	 CamelServerAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamelServerAddress;
asn_struct_free_f CamelServerAddress_free;
asn_struct_print_f CamelServerAddress_print;
asn_constr_check_f CamelServerAddress_constraint;
ber_type_decoder_f CamelServerAddress_decode_ber;
der_type_encoder_f CamelServerAddress_encode_der;
xer_type_decoder_f CamelServerAddress_decode_xer;
xer_type_encoder_f CamelServerAddress_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CamelServerAddress_H_ */
#include <asn_internal.h>
