/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_ChannelCodingAcceptableList_H_
#define	_ChannelCodingAcceptableList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChannelCoding.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChannelCodingAcceptableList */
typedef struct ChannelCodingAcceptableList {
	A_SEQUENCE_OF(ChannelCoding_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChannelCodingAcceptableList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChannelCodingAcceptableList;

#ifdef __cplusplus
}
#endif

#endif	/* _ChannelCodingAcceptableList_H_ */
#include <asn_internal.h>
