/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_DataVolumeReference_H_
#define	_DataVolumeReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DataVolumeReference */
typedef long	 DataVolumeReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataVolumeReference;
asn_struct_free_f DataVolumeReference_free;
asn_struct_print_f DataVolumeReference_print;
asn_constr_check_f DataVolumeReference_constraint;
ber_type_decoder_f DataVolumeReference_decode_ber;
der_type_encoder_f DataVolumeReference_encode_der;
xer_type_decoder_f DataVolumeReference_decode_xer;
xer_type_encoder_f DataVolumeReference_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DataVolumeReference_H_ */
#include <asn_internal.h>
