/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_DayCategorySubtype_H_
#define	_DayCategorySubtype_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DayCategorySubtype */
typedef AsciiString_t	 DayCategorySubtype_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DayCategorySubtype;
asn_struct_free_f DayCategorySubtype_free;
asn_struct_print_f DayCategorySubtype_print;
asn_constr_check_f DayCategorySubtype_constraint;
ber_type_decoder_f DayCategorySubtype_decode_ber;
der_type_encoder_f DayCategorySubtype_encode_der;
xer_type_decoder_f DayCategorySubtype_decode_xer;
xer_type_encoder_f DayCategorySubtype_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DayCategorySubtype_H_ */
#include <asn_internal.h>
