/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_DualServiceCode_H_
#define	_DualServiceCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DualTeleServiceCode.h"
#include "DualBearerServiceCode.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DualServiceCode_PR {
	DualServiceCode_PR_NOTHING,	/* No components present */
	DualServiceCode_PR_dualTeleServiceCode,
	DualServiceCode_PR_dualBearerServiceCode
} DualServiceCode_PR;

/* DualServiceCode */
typedef struct DualServiceCode {
	DualServiceCode_PR present;
	union DualServiceCode_u {
		DualTeleServiceCode_t	 dualTeleServiceCode;
		DualBearerServiceCode_t	 dualBearerServiceCode;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DualServiceCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DualServiceCode;

#ifdef __cplusplus
}
#endif

#endif	/* _DualServiceCode_H_ */
#include <asn_internal.h>
