/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_DualBearerServiceCode_H_
#define	_DualBearerServiceCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HexString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DualBearerServiceCode */
typedef HexString_t	 DualBearerServiceCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DualBearerServiceCode;
asn_struct_free_f DualBearerServiceCode_free;
asn_struct_print_f DualBearerServiceCode_print;
asn_constr_check_f DualBearerServiceCode_constraint;
ber_type_decoder_f DualBearerServiceCode_decode_ber;
der_type_encoder_f DualBearerServiceCode_encode_der;
xer_type_decoder_f DualBearerServiceCode_decode_xer;
xer_type_encoder_f DualBearerServiceCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DualBearerServiceCode_H_ */
#include <asn_internal.h>
