/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "EquipmentInformation.h"

static asn_TYPE_member_t asn_MBR_EquipmentInformation_1[] = {
	{ ATF_POINTER, 2, offsetof(struct EquipmentInformation, mobileStationClassMark),
		(ASN_TAG_CLASS_APPLICATION | (148 << 2)),
		0,
		&asn_DEF_MobileStationClassMark,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mobileStationClassMark"
		},
	{ ATF_POINTER, 1, offsetof(struct EquipmentInformation, imeiOrEsn),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ImeiOrEsn,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imeiOrEsn"
		},
};
static const ber_tlv_tag_t asn_DEF_EquipmentInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (102 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EquipmentInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (103 << 2)), 1, 0, 0 }, /* esn */
    { (ASN_TAG_CLASS_APPLICATION | (128 << 2)), 1, 0, 0 }, /* imei */
    { (ASN_TAG_CLASS_APPLICATION | (148 << 2)), 0, 0, 0 } /* mobileStationClassMark */
};
static asn_SEQUENCE_specifics_t asn_SPC_EquipmentInformation_specs_1 = {
	sizeof(struct EquipmentInformation),
	offsetof(struct EquipmentInformation, _asn_ctx),
	asn_MAP_EquipmentInformation_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EquipmentInformation = {
	"EquipmentInformation",
	"EquipmentInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EquipmentInformation_tags_1,
	sizeof(asn_DEF_EquipmentInformation_tags_1)
		/sizeof(asn_DEF_EquipmentInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_EquipmentInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_EquipmentInformation_tags_1)
		/sizeof(asn_DEF_EquipmentInformation_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_EquipmentInformation_1,
	2,	/* Elements count */
	&asn_SPC_EquipmentInformation_specs_1	/* Additional specs */
};

