/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_EquipmentInformation_H_
#define	_EquipmentInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MobileStationClassMark.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ImeiOrEsn;

/* EquipmentInformation */
typedef struct EquipmentInformation {
	MobileStationClassMark_t	*mobileStationClassMark	/* OPTIONAL */;
	struct ImeiOrEsn	*imeiOrEsn	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EquipmentInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EquipmentInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ImeiOrEsn.h"

#endif	/* _EquipmentInformation_H_ */
#include <asn_internal.h>
