/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_FraudMonitorIndicator_H_
#define	_FraudMonitorIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FraudMonitorIndicator */
typedef AsciiString_t	 FraudMonitorIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FraudMonitorIndicator;
asn_struct_free_f FraudMonitorIndicator_free;
asn_struct_print_f FraudMonitorIndicator_print;
asn_constr_check_f FraudMonitorIndicator_constraint;
ber_type_decoder_f FraudMonitorIndicator_decode_ber;
der_type_encoder_f FraudMonitorIndicator_encode_der;
xer_type_decoder_f FraudMonitorIndicator_decode_xer;
xer_type_encoder_f FraudMonitorIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FraudMonitorIndicator_H_ */
#include <asn_internal.h>
