/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_GmlcAddress_H_
#define	_GmlcAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GmlcAddress */
typedef AsciiString_t	 GmlcAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GmlcAddress;
asn_struct_free_f GmlcAddress_free;
asn_struct_print_f GmlcAddress_print;
asn_constr_check_f GmlcAddress_constraint;
ber_type_decoder_f GmlcAddress_decode_ber;
der_type_encoder_f GmlcAddress_encode_der;
xer_type_decoder_f GmlcAddress_decode_xer;
xer_type_encoder_f GmlcAddress_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _GmlcAddress_H_ */
#include <asn_internal.h>
