/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "GprsServiceUsage.h"

static asn_TYPE_member_t asn_MBR_GprsServiceUsage_1[] = {
	{ ATF_POINTER, 5, offsetof(struct GprsServiceUsage, gprsUsageTimeStamp),
		(ASN_TAG_CLASS_APPLICATION | (74 << 2)),
		0,
		&asn_DEF_ChargingTimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gprsUsageTimeStamp"
		},
	{ ATF_POINTER, 4, offsetof(struct GprsServiceUsage, qosRequested),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_QoSRequested,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"qosRequested"
		},
	{ ATF_POINTER, 3, offsetof(struct GprsServiceUsage, qosUsed),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_QoSUsed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"qosUsed"
		},
	{ ATF_POINTER, 2, offsetof(struct GprsServiceUsage, dataVolumeIncoming),
		(ASN_TAG_CLASS_APPLICATION | (250 << 2)),
		0,
		&asn_DEF_DataVolumeIncoming,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeIncoming"
		},
	{ ATF_POINTER, 1, offsetof(struct GprsServiceUsage, dataVolumeOutgoing),
		(ASN_TAG_CLASS_APPLICATION | (251 << 2)),
		0,
		&asn_DEF_DataVolumeOutgoing,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataVolumeOutgoing"
		},
};
static const ber_tlv_tag_t asn_DEF_GprsServiceUsage_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (119 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GprsServiceUsage_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (74 << 2)), 0, 0, 0 }, /* gprsUsageTimeStamp */
    { (ASN_TAG_CLASS_APPLICATION | (250 << 2)), 3, 0, 0 }, /* dataVolumeIncoming */
    { (ASN_TAG_CLASS_APPLICATION | (251 << 2)), 4, 0, 0 }, /* dataVolumeOutgoing */
    { (ASN_TAG_CLASS_APPLICATION | (270 << 2)), 1, 0, 0 }, /* umtsQoSRequested */
    { (ASN_TAG_CLASS_APPLICATION | (271 << 2)), 2, 0, 0 }, /* umtsQoSUsed */
    { (ASN_TAG_CLASS_APPLICATION | (272 << 2)), 1, 0, 0 }, /* gsmQoSRequested */
    { (ASN_TAG_CLASS_APPLICATION | (273 << 2)), 2, 0, 0 } /* gsmQoSUsed */
};
static asn_SEQUENCE_specifics_t asn_SPC_GprsServiceUsage_specs_1 = {
	sizeof(struct GprsServiceUsage),
	offsetof(struct GprsServiceUsage, _asn_ctx),
	asn_MAP_GprsServiceUsage_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GprsServiceUsage = {
	"GprsServiceUsage",
	"GprsServiceUsage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GprsServiceUsage_tags_1,
	sizeof(asn_DEF_GprsServiceUsage_tags_1)
		/sizeof(asn_DEF_GprsServiceUsage_tags_1[0]) - 1, /* 1 */
	asn_DEF_GprsServiceUsage_tags_1,	/* Same as above */
	sizeof(asn_DEF_GprsServiceUsage_tags_1)
		/sizeof(asn_DEF_GprsServiceUsage_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_GprsServiceUsage_1,
	5,	/* Elements count */
	&asn_SPC_GprsServiceUsage_specs_1	/* Additional specs */
};

