/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "GSMQoSInformation.h"

static asn_TYPE_member_t asn_MBR_GSMQoSInformation_1[] = {
	{ ATF_POINTER, 5, offsetof(struct GSMQoSInformation, delay),
		(ASN_TAG_CLASS_APPLICATION | (171 << 2)),
		0,
		&asn_DEF_QoSDelay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"delay"
		},
	{ ATF_POINTER, 4, offsetof(struct GSMQoSInformation, meanThroughput),
		(ASN_TAG_CLASS_APPLICATION | (173 << 2)),
		0,
		&asn_DEF_QoSMeanThroughput,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"meanThroughput"
		},
	{ ATF_POINTER, 3, offsetof(struct GSMQoSInformation, peakThroughput),
		(ASN_TAG_CLASS_APPLICATION | (174 << 2)),
		0,
		&asn_DEF_QoSPeakThroughput,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"peakThroughput"
		},
	{ ATF_POINTER, 2, offsetof(struct GSMQoSInformation, precedence),
		(ASN_TAG_CLASS_APPLICATION | (175 << 2)),
		0,
		&asn_DEF_QoSPrecedence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"precedence"
		},
	{ ATF_POINTER, 1, offsetof(struct GSMQoSInformation, reliability),
		(ASN_TAG_CLASS_APPLICATION | (176 << 2)),
		0,
		&asn_DEF_QoSReliability,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"reliability"
		},
};
static const ber_tlv_tag_t asn_DEF_GSMQoSInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GSMQoSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (171 << 2)), 0, 0, 0 }, /* delay */
    { (ASN_TAG_CLASS_APPLICATION | (173 << 2)), 1, 0, 0 }, /* meanThroughput */
    { (ASN_TAG_CLASS_APPLICATION | (174 << 2)), 2, 0, 0 }, /* peakThroughput */
    { (ASN_TAG_CLASS_APPLICATION | (175 << 2)), 3, 0, 0 }, /* precedence */
    { (ASN_TAG_CLASS_APPLICATION | (176 << 2)), 4, 0, 0 } /* reliability */
};
static asn_SEQUENCE_specifics_t asn_SPC_GSMQoSInformation_specs_1 = {
	sizeof(struct GSMQoSInformation),
	offsetof(struct GSMQoSInformation, _asn_ctx),
	asn_MAP_GSMQoSInformation_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GSMQoSInformation = {
	"GSMQoSInformation",
	"GSMQoSInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GSMQoSInformation_tags_1,
	sizeof(asn_DEF_GSMQoSInformation_tags_1)
		/sizeof(asn_DEF_GSMQoSInformation_tags_1[0]), /* 1 */
	asn_DEF_GSMQoSInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_GSMQoSInformation_tags_1)
		/sizeof(asn_DEF_GSMQoSInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GSMQoSInformation_1,
	5,	/* Elements count */
	&asn_SPC_GSMQoSInformation_specs_1	/* Additional specs */
};

