/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_GSMQoSInformation_H_
#define	_GSMQoSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QoSDelay.h"
#include "QoSMeanThroughput.h"
#include "QoSPeakThroughput.h"
#include "QoSPrecedence.h"
#include "QoSReliability.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GSMQoSInformation */
typedef struct GSMQoSInformation {
	QoSDelay_t	*delay	/* OPTIONAL */;
	QoSMeanThroughput_t	*meanThroughput	/* OPTIONAL */;
	QoSPeakThroughput_t	*peakThroughput	/* OPTIONAL */;
	QoSPrecedence_t	*precedence	/* OPTIONAL */;
	QoSReliability_t	*reliability	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GSMQoSInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GSMQoSInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _GSMQoSInformation_H_ */
#include <asn_internal.h>
