/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_GsnAddress_H_
#define	_GsnAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IpAddress.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GsnAddress */
typedef IpAddress_t	 GsnAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GsnAddress;
asn_struct_free_f GsnAddress_free;
asn_struct_print_f GsnAddress_print;
asn_constr_check_f GsnAddress_constraint;
ber_type_decoder_f GsnAddress_decode_ber;
der_type_encoder_f GsnAddress_encode_der;
xer_type_decoder_f GsnAddress_decode_xer;
xer_type_encoder_f GsnAddress_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _GsnAddress_H_ */
#include <asn_internal.h>
