/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_IPTextV6Address_H_
#define	_IPTextV6Address_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* IPTextV6Address */
typedef AsciiString_t	 IPTextV6Address_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IPTextV6Address;
asn_struct_free_f IPTextV6Address_free;
asn_struct_print_f IPTextV6Address_print;
asn_constr_check_f IPTextV6Address_constraint;
ber_type_decoder_f IPTextV6Address_decode_ber;
der_type_encoder_f IPTextV6Address_encode_der;
xer_type_decoder_f IPTextV6Address_decode_xer;
xer_type_encoder_f IPTextV6Address_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IPTextV6Address_H_ */
#include <asn_internal.h>
