/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_MobileStationClassMark_H_
#define	_MobileStationClassMark_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MobileStationClassMark */
typedef long	 MobileStationClassMark_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MobileStationClassMark;
asn_struct_free_f MobileStationClassMark_free;
asn_struct_print_f MobileStationClassMark_print;
asn_constr_check_f MobileStationClassMark_constraint;
ber_type_decoder_f MobileStationClassMark_decode_ber;
der_type_encoder_f MobileStationClassMark_encode_der;
xer_type_decoder_f MobileStationClassMark_decode_xer;
xer_type_encoder_f MobileStationClassMark_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MobileStationClassMark_H_ */
#include <asn_internal.h>
