/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_ModificationTimestamp_H_
#define	_ModificationTimestamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DateTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ModificationTimestamp */
typedef DateTime_t	 ModificationTimestamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModificationTimestamp;
asn_struct_free_f ModificationTimestamp_free;
asn_struct_print_f ModificationTimestamp_print;
asn_constr_check_f ModificationTimestamp_constraint;
ber_type_decoder_f ModificationTimestamp_decode_ber;
der_type_encoder_f ModificationTimestamp_encode_der;
xer_type_decoder_f ModificationTimestamp_decode_xer;
xer_type_encoder_f ModificationTimestamp_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ModificationTimestamp_H_ */
#include <asn_internal.h>
