/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_MultiRateIndicator_H_
#define	_MultiRateIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MultiRateIndicator */
typedef long	 MultiRateIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultiRateIndicator;
asn_struct_free_f MultiRateIndicator_free;
asn_struct_print_f MultiRateIndicator_print;
asn_constr_check_f MultiRateIndicator_constraint;
ber_type_decoder_f MultiRateIndicator_decode_ber;
der_type_encoder_f MultiRateIndicator_encode_der;
xer_type_decoder_f MultiRateIndicator_decode_xer;
xer_type_encoder_f MultiRateIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiRateIndicator_H_ */
#include <asn_internal.h>
