/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_QoSDelay_H_
#define	_QoSDelay_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* QoSDelay */
typedef long	 QoSDelay_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSDelay;
asn_struct_free_f QoSDelay_free;
asn_struct_print_f QoSDelay_print;
asn_constr_check_f QoSDelay_constraint;
ber_type_decoder_f QoSDelay_decode_ber;
der_type_encoder_f QoSDelay_encode_der;
xer_type_decoder_f QoSDelay_decode_xer;
xer_type_encoder_f QoSDelay_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSDelay_H_ */
#include <asn_internal.h>
