/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_QoSMaxBitRateDownlink_H_
#define	_QoSMaxBitRateDownlink_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* QoSMaxBitRateDownlink */
typedef OCTET_STRING_t	 QoSMaxBitRateDownlink_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSMaxBitRateDownlink;
asn_struct_free_f QoSMaxBitRateDownlink_free;
asn_struct_print_f QoSMaxBitRateDownlink_print;
asn_constr_check_f QoSMaxBitRateDownlink_constraint;
ber_type_decoder_f QoSMaxBitRateDownlink_decode_ber;
der_type_encoder_f QoSMaxBitRateDownlink_encode_der;
xer_type_decoder_f QoSMaxBitRateDownlink_decode_xer;
xer_type_encoder_f QoSMaxBitRateDownlink_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSMaxBitRateDownlink_H_ */
#include <asn_internal.h>
