/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_QoSUsed_H_
#define	_QoSUsed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GSMQoSUsed.h"
#include "UMTSQoSUsed.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QoSUsed_PR {
	QoSUsed_PR_NOTHING,	/* No components present */
	QoSUsed_PR_gsmQoSUsed,
	QoSUsed_PR_umtsQoSUsed
} QoSUsed_PR;

/* QoSUsed */
typedef struct QoSUsed {
	QoSUsed_PR present;
	union QoSUsed_u {
		GSMQoSUsed_t	 gsmQoSUsed;
		UMTSQoSUsed_t	 umtsQoSUsed;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QoSUsed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSUsed;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSUsed_H_ */
#include <asn_internal.h>
