/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "QoSUsed.h"

static asn_TYPE_member_t asn_MBR_QoSUsed_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct QoSUsed, choice.gsmQoSUsed),
		(ASN_TAG_CLASS_APPLICATION | (273 << 2)),
		0,
		&asn_DEF_GSMQoSUsed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gsmQoSUsed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct QoSUsed, choice.umtsQoSUsed),
		(ASN_TAG_CLASS_APPLICATION | (271 << 2)),
		0,
		&asn_DEF_UMTSQoSUsed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"umtsQoSUsed"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_QoSUsed_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (271 << 2)), 1, 0, 0 }, /* umtsQoSUsed */
    { (ASN_TAG_CLASS_APPLICATION | (273 << 2)), 0, 0, 0 } /* gsmQoSUsed */
};
static asn_CHOICE_specifics_t asn_SPC_QoSUsed_specs_1 = {
	sizeof(struct QoSUsed),
	offsetof(struct QoSUsed, _asn_ctx),
	offsetof(struct QoSUsed, present),
	sizeof(((struct QoSUsed *)0)->present),
	asn_MAP_QoSUsed_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_QoSUsed = {
	"QoSUsed",
	"QoSUsed",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_QoSUsed_1,
	2,	/* Elements count */
	&asn_SPC_QoSUsed_specs_1	/* Additional specs */
};

