/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_ScuVasChargeableSubscriber_H_
#define	_ScuVasChargeableSubscriber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GsmChargeableSubscriber.h"
#include "MinChargeableSubscriber.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ScuVasChargeableSubscriber_PR {
	ScuVasChargeableSubscriber_PR_NOTHING,	/* No components present */
	ScuVasChargeableSubscriber_PR_gsmChargeableSubscriber,
	ScuVasChargeableSubscriber_PR_minChargeableSubscriber
} ScuVasChargeableSubscriber_PR;

/* ScuVasChargeableSubscriber */
typedef struct ScuVasChargeableSubscriber {
	ScuVasChargeableSubscriber_PR present;
	union ScuVasChargeableSubscriber_u {
		GsmChargeableSubscriber_t	 gsmChargeableSubscriber;
		MinChargeableSubscriber_t	 minChargeableSubscriber;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScuVasChargeableSubscriber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScuVasChargeableSubscriber;

#ifdef __cplusplus
}
#endif

#endif	/* _ScuVasChargeableSubscriber_H_ */
#include <asn_internal.h>
