/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "ScuVasChargeableSubscriber.h"

static asn_TYPE_member_t asn_MBR_ScuVasChargeableSubscriber_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ScuVasChargeableSubscriber, choice.gsmChargeableSubscriber),
		(ASN_TAG_CLASS_APPLICATION | (286 << 2)),
		0,
		&asn_DEF_GsmChargeableSubscriber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"gsmChargeableSubscriber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ScuVasChargeableSubscriber, choice.minChargeableSubscriber),
		(ASN_TAG_CLASS_APPLICATION | (254 << 2)),
		0,
		&asn_DEF_MinChargeableSubscriber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"minChargeableSubscriber"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ScuVasChargeableSubscriber_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (254 << 2)), 1, 0, 0 }, /* minChargeableSubscriber */
    { (ASN_TAG_CLASS_APPLICATION | (286 << 2)), 0, 0, 0 } /* gsmChargeableSubscriber */
};
static asn_CHOICE_specifics_t asn_SPC_ScuVasChargeableSubscriber_specs_1 = {
	sizeof(struct ScuVasChargeableSubscriber),
	offsetof(struct ScuVasChargeableSubscriber, _asn_ctx),
	offsetof(struct ScuVasChargeableSubscriber, present),
	sizeof(((struct ScuVasChargeableSubscriber *)0)->present),
	asn_MAP_ScuVasChargeableSubscriber_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ScuVasChargeableSubscriber = {
	"ScuVasChargeableSubscriber",
	"ScuVasChargeableSubscriber",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ScuVasChargeableSubscriber_1,
	2,	/* Elements count */
	&asn_SPC_ScuVasChargeableSubscriber_specs_1	/* Additional specs */
};

