/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_SpeechVersionRequested_H_
#define	_SpeechVersionRequested_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SpeechVersion.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SpeechVersionRequested */
typedef SpeechVersion_t	 SpeechVersionRequested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeechVersionRequested;
asn_struct_free_f SpeechVersionRequested_free;
asn_struct_print_f SpeechVersionRequested_print;
asn_constr_check_f SpeechVersionRequested_constraint;
ber_type_decoder_f SpeechVersionRequested_decode_ber;
der_type_encoder_f SpeechVersionRequested_encode_der;
xer_type_decoder_f SpeechVersionRequested_decode_xer;
xer_type_encoder_f SpeechVersionRequested_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeechVersionRequested_H_ */
#include <asn_internal.h>
