/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "TotalChargeValueList.h"

static asn_TYPE_member_t asn_MBR_TotalChargeValueList_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_APPLICATION | (222 << 2)),
		0,
		&asn_DEF_TotalChargeValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_TotalChargeValueList_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (224 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_TotalChargeValueList_specs_1 = {
	sizeof(struct TotalChargeValueList),
	offsetof(struct TotalChargeValueList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_TotalChargeValueList = {
	"TotalChargeValueList",
	"TotalChargeValueList",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TotalChargeValueList_tags_1,
	sizeof(asn_DEF_TotalChargeValueList_tags_1)
		/sizeof(asn_DEF_TotalChargeValueList_tags_1[0]) - 1, /* 1 */
	asn_DEF_TotalChargeValueList_tags_1,	/* Same as above */
	sizeof(asn_DEF_TotalChargeValueList_tags_1)
		/sizeof(asn_DEF_TotalChargeValueList_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_TotalChargeValueList_1,
	1,	/* Single element */
	&asn_SPC_TotalChargeValueList_specs_1	/* Additional specs */
};

