/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_TypeOfControllingNode_H_
#define	_TypeOfControllingNode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TypeOfControllingNode */
typedef long	 TypeOfControllingNode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TypeOfControllingNode;
asn_struct_free_f TypeOfControllingNode_free;
asn_struct_print_f TypeOfControllingNode_print;
asn_constr_check_f TypeOfControllingNode_constraint;
ber_type_decoder_f TypeOfControllingNode_decode_ber;
der_type_encoder_f TypeOfControllingNode_encode_der;
xer_type_decoder_f TypeOfControllingNode_decode_xer;
xer_type_encoder_f TypeOfControllingNode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TypeOfControllingNode_H_ */
#include <asn_internal.h>
