/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "UMTSQoSInformation.h"

static asn_TYPE_member_t asn_MBR_UMTSQoSInformation_1[] = {
	{ ATF_POINTER, 6, offsetof(struct UMTSQoSInformation, trafficClass),
		(ASN_TAG_CLASS_APPLICATION | (268 << 2)),
		0,
		&asn_DEF_QoSTrafficClass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trafficClass"
		},
	{ ATF_POINTER, 5, offsetof(struct UMTSQoSInformation, maxBitRateUplink),
		(ASN_TAG_CLASS_APPLICATION | (264 << 2)),
		0,
		&asn_DEF_QoSMaxBitRateUplink,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"maxBitRateUplink"
		},
	{ ATF_POINTER, 4, offsetof(struct UMTSQoSInformation, maxBitRateDownlink),
		(ASN_TAG_CLASS_APPLICATION | (274 << 2)),
		0,
		&asn_DEF_QoSMaxBitRateDownlink,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"maxBitRateDownlink"
		},
	{ ATF_POINTER, 3, offsetof(struct UMTSQoSInformation, qoSGuaranteedBitRateDownlink),
		(ASN_TAG_CLASS_APPLICATION | (283 << 2)),
		0,
		&asn_DEF_QoSGuaranteedBitRateDownlink,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"qoSGuaranteedBitRateDownlink"
		},
	{ ATF_POINTER, 2, offsetof(struct UMTSQoSInformation, qoSGuaranteedBitRateUplink),
		(ASN_TAG_CLASS_APPLICATION | (284 << 2)),
		0,
		&asn_DEF_QoSGuaranteedBitRateUplink,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"qoSGuaranteedBitRateUplink"
		},
	{ ATF_POINTER, 1, offsetof(struct UMTSQoSInformation, allocRetenPriority),
		(ASN_TAG_CLASS_APPLICATION | (275 << 2)),
		0,
		&asn_DEF_QoSAllocRetenPriority,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"allocRetenPriority"
		},
};
static const ber_tlv_tag_t asn_DEF_UMTSQoSInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UMTSQoSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (264 << 2)), 1, 0, 0 }, /* maxBitRateUplink */
    { (ASN_TAG_CLASS_APPLICATION | (268 << 2)), 0, 0, 0 }, /* trafficClass */
    { (ASN_TAG_CLASS_APPLICATION | (274 << 2)), 2, 0, 0 }, /* maxBitRateDownlink */
    { (ASN_TAG_CLASS_APPLICATION | (275 << 2)), 5, 0, 0 }, /* allocRetenPriority */
    { (ASN_TAG_CLASS_APPLICATION | (283 << 2)), 3, 0, 0 }, /* qoSGuaranteedBitRateDownlink */
    { (ASN_TAG_CLASS_APPLICATION | (284 << 2)), 4, 0, 0 } /* qoSGuaranteedBitRateUplink */
};
static asn_SEQUENCE_specifics_t asn_SPC_UMTSQoSInformation_specs_1 = {
	sizeof(struct UMTSQoSInformation),
	offsetof(struct UMTSQoSInformation, _asn_ctx),
	asn_MAP_UMTSQoSInformation_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UMTSQoSInformation = {
	"UMTSQoSInformation",
	"UMTSQoSInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UMTSQoSInformation_tags_1,
	sizeof(asn_DEF_UMTSQoSInformation_tags_1)
		/sizeof(asn_DEF_UMTSQoSInformation_tags_1[0]), /* 1 */
	asn_DEF_UMTSQoSInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_UMTSQoSInformation_tags_1)
		/sizeof(asn_DEF_UMTSQoSInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UMTSQoSInformation_1,
	6,	/* Elements count */
	&asn_SPC_UMTSQoSInformation_specs_1	/* Additional specs */
};

