/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_UMTSQoSUsed_H_
#define	_UMTSQoSUsed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UMTSQoSInformation.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UMTSQoSUsed */
typedef UMTSQoSInformation_t	 UMTSQoSUsed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UMTSQoSUsed;
asn_struct_free_f UMTSQoSUsed_free;
asn_struct_print_f UMTSQoSUsed_print;
asn_constr_check_f UMTSQoSUsed_constraint;
ber_type_decoder_f UMTSQoSUsed_decode_ber;
der_type_encoder_f UMTSQoSUsed_encode_der;
xer_type_decoder_f UMTSQoSUsed_decode_xer;
xer_type_encoder_f UMTSQoSUsed_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UMTSQoSUsed_H_ */
#include <asn_internal.h>
