/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_UMTSQoSInformation_H_
#define	_UMTSQoSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QoSTrafficClass.h"
#include "QoSMaxBitRateUplink.h"
#include "QoSMaxBitRateDownlink.h"
#include "QoSGuaranteedBitRateDownlink.h"
#include "QoSGuaranteedBitRateUplink.h"
#include "QoSAllocRetenPriority.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UMTSQoSInformation */
typedef struct UMTSQoSInformation {
	QoSTrafficClass_t	*trafficClass	/* OPTIONAL */;
	QoSMaxBitRateUplink_t	*maxBitRateUplink	/* OPTIONAL */;
	QoSMaxBitRateDownlink_t	*maxBitRateDownlink	/* OPTIONAL */;
	QoSGuaranteedBitRateDownlink_t	*qoSGuaranteedBitRateDownlink	/* OPTIONAL */;
	QoSGuaranteedBitRateUplink_t	*qoSGuaranteedBitRateUplink	/* OPTIONAL */;
	QoSAllocRetenPriority_t	*allocRetenPriority	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UMTSQoSInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UMTSQoSInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _UMTSQoSInformation_H_ */
#include <asn_internal.h>
