/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_ValueAddedServiceUsed_H_
#define	_ValueAddedServiceUsed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VasCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DateTime;
struct ChargeInformation;

/* ValueAddedServiceUsed */
typedef struct ValueAddedServiceUsed {
	VasCode_t	*vasCode	/* OPTIONAL */;
	struct DateTime	*chargingTimeStamp	/* OPTIONAL */;
	struct ChargeInformation	*chargeInformation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ValueAddedServiceUsed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ValueAddedServiceUsed;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargingTimeStamp.h"
#include "ChargeInformation.h"

#endif	/* _ValueAddedServiceUsed_H_ */
#include <asn_internal.h>
