/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "ValueAddedService.h"

static asn_TYPE_member_t asn_MBR_ValueAddedService_1[] = {
	{ ATF_POINTER, 7, offsetof(struct ValueAddedService, fraudMonitorIndicator),
		(ASN_TAG_CLASS_APPLICATION | (112 << 2)),
		0,
		&asn_DEF_FraudMonitorIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fraudMonitorIndicator"
		},
	{ ATF_POINTER, 6, offsetof(struct ValueAddedService, chargeableSubscriber),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ScuVasChargeableSubscriber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargeableSubscriber"
		},
	{ ATF_POINTER, 5, offsetof(struct ValueAddedService, rapFileSequenceNumber),
		(ASN_TAG_CLASS_APPLICATION | (181 << 2)),
		0,
		&asn_DEF_RapFileSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rapFileSequenceNumber"
		},
	{ ATF_POINTER, 4, offsetof(struct ValueAddedService, networkType),
		(ASN_TAG_CLASS_APPLICATION | (157 << 2)),
		0,
		&asn_DEF_NetworkType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkType"
		},
	{ ATF_POINTER, 3, offsetof(struct ValueAddedService, servingNetwork),
		(ASN_TAG_CLASS_APPLICATION | (195 << 2)),
		0,
		&asn_DEF_ServingNetwork,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servingNetwork"
		},
	{ ATF_POINTER, 2, offsetof(struct ValueAddedService, valueAddedServiceUsed),
		(ASN_TAG_CLASS_APPLICATION | (236 << 2)),
		0,
		&asn_DEF_ValueAddedServiceUsed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"valueAddedServiceUsed"
		},
	{ ATF_POINTER, 1, offsetof(struct ValueAddedService, operatorSpecInformation),
		(ASN_TAG_CLASS_APPLICATION | (162 << 2)),
		0,
		&asn_DEF_OperatorSpecInfoList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"operatorSpecInformation"
		},
};
static const ber_tlv_tag_t asn_DEF_ValueAddedService_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (13 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ValueAddedService_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (112 << 2)), 0, 0, 0 }, /* fraudMonitorIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (157 << 2)), 3, 0, 0 }, /* networkType */
    { (ASN_TAG_CLASS_APPLICATION | (162 << 2)), 6, 0, 0 }, /* operatorSpecInformation */
    { (ASN_TAG_CLASS_APPLICATION | (181 << 2)), 2, 0, 0 }, /* rapFileSequenceNumber */
    { (ASN_TAG_CLASS_APPLICATION | (195 << 2)), 4, 0, 0 }, /* servingNetwork */
    { (ASN_TAG_CLASS_APPLICATION | (236 << 2)), 5, 0, 0 }, /* valueAddedServiceUsed */
    { (ASN_TAG_CLASS_APPLICATION | (254 << 2)), 1, 0, 0 }, /* minChargeableSubscriber */
    { (ASN_TAG_CLASS_APPLICATION | (286 << 2)), 1, 0, 0 } /* gsmChargeableSubscriber */
};
static asn_SEQUENCE_specifics_t asn_SPC_ValueAddedService_specs_1 = {
	sizeof(struct ValueAddedService),
	offsetof(struct ValueAddedService, _asn_ctx),
	asn_MAP_ValueAddedService_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ValueAddedService = {
	"ValueAddedService",
	"ValueAddedService",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ValueAddedService_tags_1,
	sizeof(asn_DEF_ValueAddedService_tags_1)
		/sizeof(asn_DEF_ValueAddedService_tags_1[0]) - 1, /* 1 */
	asn_DEF_ValueAddedService_tags_1,	/* Same as above */
	sizeof(asn_DEF_ValueAddedService_tags_1)
		/sizeof(asn_DEF_ValueAddedService_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ValueAddedService_1,
	7,	/* Elements count */
	&asn_SPC_ValueAddedService_specs_1	/* Additional specs */
};

