/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_ValueAddedService_H_
#define	_ValueAddedService_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FraudMonitorIndicator.h"
#include "RapFileSequenceNumber.h"
#include "NetworkType.h"
#include "ServingNetwork.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ScuVasChargeableSubscriber;
struct ValueAddedServiceUsed;
struct OperatorSpecInfoList;

/* ValueAddedService */
typedef struct ValueAddedService {
	FraudMonitorIndicator_t	*fraudMonitorIndicator	/* OPTIONAL */;
	struct ScuVasChargeableSubscriber	*chargeableSubscriber	/* OPTIONAL */;
	RapFileSequenceNumber_t	*rapFileSequenceNumber	/* OPTIONAL */;
	NetworkType_t	*networkType	/* OPTIONAL */;
	ServingNetwork_t	*servingNetwork	/* OPTIONAL */;
	struct ValueAddedServiceUsed	*valueAddedServiceUsed	/* OPTIONAL */;
	struct OperatorSpecInfoList	*operatorSpecInformation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ValueAddedService_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ValueAddedService;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ScuVasChargeableSubscriber.h"
#include "ValueAddedServiceUsed.h"
#include "OperatorSpecInfoList.h"

#endif	/* _ValueAddedService_H_ */
#include <asn_internal.h>
