/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#include "VasInformation.h"

static asn_TYPE_member_t asn_MBR_VasInformation_1[] = {
	{ ATF_POINTER, 3, offsetof(struct VasInformation, vasCode),
		(ASN_TAG_CLASS_APPLICATION | (237 << 2)),
		0,
		&asn_DEF_VasCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vasCode"
		},
	{ ATF_POINTER, 2, offsetof(struct VasInformation, vasShortDesc),
		(ASN_TAG_CLASS_APPLICATION | (240 << 2)),
		0,
		&asn_DEF_VasShortDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vasShortDesc"
		},
	{ ATF_POINTER, 1, offsetof(struct VasInformation, vasDesc),
		(ASN_TAG_CLASS_APPLICATION | (239 << 2)),
		0,
		&asn_DEF_VasDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vasDesc"
		},
};
static const ber_tlv_tag_t asn_DEF_VasInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (238 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VasInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (237 << 2)), 0, 0, 0 }, /* vasCode */
    { (ASN_TAG_CLASS_APPLICATION | (239 << 2)), 2, 0, 0 }, /* vasDesc */
    { (ASN_TAG_CLASS_APPLICATION | (240 << 2)), 1, 0, 0 } /* vasShortDesc */
};
static asn_SEQUENCE_specifics_t asn_SPC_VasInformation_specs_1 = {
	sizeof(struct VasInformation),
	offsetof(struct VasInformation, _asn_ctx),
	asn_MAP_VasInformation_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VasInformation = {
	"VasInformation",
	"VasInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VasInformation_tags_1,
	sizeof(asn_DEF_VasInformation_tags_1)
		/sizeof(asn_DEF_VasInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_VasInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_VasInformation_tags_1)
		/sizeof(asn_DEF_VasInformation_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_VasInformation_1,
	3,	/* Elements count */
	&asn_SPC_VasInformation_specs_1	/* Additional specs */
};

