/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0310"
 * 	found in "../tap3.asn1"
 * 	`asn1c -S ../../skeletons`
 */

#ifndef	_VasInformation_H_
#define	_VasInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VasCode.h"
#include "VasShortDescription.h"
#include "VasDescription.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VasInformation */
typedef struct VasInformation {
	VasCode_t	*vasCode	/* OPTIONAL */;
	VasShortDescription_t	*vasShortDesc	/* OPTIONAL */;
	VasDescription_t	*vasDesc	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VasInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VasInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _VasInformation_H_ */
#include <asn_internal.h>
