/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_Crl_H_
#define	_Crl_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint32.h"
#include "SignerInfo.h"
#include "ToBeSignedCrl.h"
#include "Signature.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Crl */
typedef struct Crl {
	Uint32_t	 version;
	SignerInfo_t	 signerInfo;
	ToBeSignedCrl_t	 unsignedCrl;
	Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Crl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Crl;

#ifdef __cplusplus
}
#endif

#endif	/* _Crl_H_ */
#include "asn_internal.h"
