/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_EncryptKey_H_
#define	_EncryptKey_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SymmetricAlgorithm.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EncryptKey */
typedef struct EncryptKey {
	SymmetricAlgorithm_t	 supportedSymmAlg;
	OCTET_STRING_t	 signKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncryptKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptKey;

#ifdef __cplusplus
}
#endif

#endif	/* _EncryptKey_H_ */
#include "asn_internal.h"
