/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_GeographicRegion_H_
#define	_GeographicRegion_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CircularRegion.h"
#include "SequenceOfRectangularRegion.h"
#include "PolygonalRegion.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GeographicRegion_PR {
	GeographicRegion_PR_NOTHING,	/* No components present */
	GeographicRegion_PR_circularRegion,
	GeographicRegion_PR_rectangularRegion,
	GeographicRegion_PR_polygonalRegion,
	/* Extensions may appear below */
	
} GeographicRegion_PR;

/* GeographicRegion */
typedef struct GeographicRegion {
	GeographicRegion_PR present;
	union GeographicRegion_u {
		CircularRegion_t	 circularRegion;
		SequenceOfRectangularRegion_t	 rectangularRegion;
		PolygonalRegion_t	 polygonalRegion;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeographicRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeographicRegion;

#ifdef __cplusplus
}
#endif

#endif	/* _GeographicRegion_H_ */
#include "asn_internal.h"
