/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_HashedId10_H_
#define	_HashedId10_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* HashedId10 */
typedef OCTET_STRING_t	 HashedId10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HashedId10;
asn_struct_free_f HashedId10_free;
asn_struct_print_f HashedId10_print;
asn_constr_check_f HashedId10_constraint;
ber_type_decoder_f HashedId10_decode_ber;
der_type_encoder_f HashedId10_encode_der;
xer_type_decoder_f HashedId10_decode_xer;
xer_type_encoder_f HashedId10_encode_xer;
per_type_decoder_f HashedId10_decode_uper;
per_type_encoder_f HashedId10_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HashedId10_H_ */
#include "asn_internal.h"
