/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_IdAndDate_H_
#define	_IdAndDate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "HashedId10.h"
#include "Time32.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* IdAndDate */
typedef struct IdAndDate {
	HashedId10_t	 id;
	Time32_t	 expiry;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IdAndDate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IdAndDate;

#ifdef __cplusplus
}
#endif

#endif	/* _IdAndDate_H_ */
#include "asn_internal.h"
