/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_IValue_H_
#define	_IValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint16.h"

#ifdef __cplusplus
extern "C" {
#endif

/* IValue */
typedef Uint16_t	 IValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IValue;
asn_struct_free_f IValue_free;
asn_struct_print_f IValue_print;
asn_constr_check_f IValue_constraint;
ber_type_decoder_f IValue_decode_ber;
der_type_encoder_f IValue_encode_der;
xer_type_decoder_f IValue_decode_xer;
xer_type_encoder_f IValue_encode_xer;
per_type_decoder_f IValue_decode_uper;
per_type_encoder_f IValue_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IValue_H_ */
#include "asn_internal.h"
