ASN_MODULE_SOURCES=	\
	Uint3.c	\
	Uint8.c	\
	Uint16.c	\
	Uint32.c	\
	IValue.c	\
	CrlSeries.c	\
	Opaque.c	\
	SequenceOfOctetString.c	\
	SequenceOfUint3.c	\
	SequenceOfUint8.c	\
	SequenceOfUint16.c	\
	PublicKeyAlgorithm.c	\
	SymmetricAlgorithm.c	\
	PublicKey.c	\
	EncryptKey.c	\
	HashedId8.c	\
	HashedId10.c	\
	Time32.c	\
	Duration.c	\
	GeographicRegion.c	\
	SequenceOfRectangularRegion.c	\
	CircularRegion.c	\
	RectangularRegion.c	\
	PolygonalRegion.c	\
	TwoDLocation.c	\
	Latitude.c	\
	NinetyDegreeInt.c	\
	KnownLatitude.c	\
	UnknownLatitude.c	\
	Longitude.c	\
	OneEightyDegreeInt.c	\
	KnownLongitude.c	\
	UnknownLongitude.c	\
	Certificate.c	\
	SignerInfo.c	\
	SequenceOfCertificate.c	\
	CertificateDigestWithOtherAlgorithm.c	\
	SubjectInfo.c	\
	SubjectType.c	\
	SubjectAttribute.c	\
	SubjectAssurance.c	\
	SequenceOfitsAidList.c	\
	SequenceOfitsAidSspList.c	\
	ItsAid.c	\
	ItsAidSsp.c	\
	ValidityRestriction.c	\
	SequenceOfTimeStartAndEnd.c	\
	SequenceOfTimestartAndDuration.c	\
	Signature.c	\
	Crl.c	\
	ToBeSignedCrl.c	\
	CrlType.c	\
	IdAndDate.c

ASN_MODULE_HEADERS=	\
	Uint3.h	\
	Uint8.h	\
	Uint16.h	\
	Uint32.h	\
	IValue.h	\
	CrlSeries.h	\
	Opaque.h	\
	SequenceOfOctetString.h	\
	SequenceOfUint3.h	\
	SequenceOfUint8.h	\
	SequenceOfUint16.h	\
	PublicKeyAlgorithm.h	\
	SymmetricAlgorithm.h	\
	PublicKey.h	\
	EncryptKey.h	\
	HashedId8.h	\
	HashedId10.h	\
	Time32.h	\
	Duration.h	\
	GeographicRegion.h	\
	SequenceOfRectangularRegion.h	\
	CircularRegion.h	\
	RectangularRegion.h	\
	PolygonalRegion.h	\
	TwoDLocation.h	\
	Latitude.h	\
	NinetyDegreeInt.h	\
	KnownLatitude.h	\
	UnknownLatitude.h	\
	Longitude.h	\
	OneEightyDegreeInt.h	\
	KnownLongitude.h	\
	UnknownLongitude.h	\
	Certificate.h	\
	SignerInfo.h	\
	SequenceOfCertificate.h	\
	CertificateDigestWithOtherAlgorithm.h	\
	SubjectInfo.h	\
	SubjectType.h	\
	SubjectAttribute.h	\
	SubjectAssurance.h	\
	SequenceOfitsAidList.h	\
	SequenceOfitsAidSspList.h	\
	ItsAid.h	\
	ItsAidSsp.h	\
	ValidityRestriction.h	\
	SequenceOfTimeStartAndEnd.h	\
	SequenceOfTimestartAndDuration.h	\
	Signature.h	\
	Crl.h	\
	ToBeSignedCrl.h	\
	CrlType.h	\
	IdAndDate.h

ASN_MODULE_HEADERS+=BOOLEAN.h
ASN_MODULE_SOURCES+=BOOLEAN.c
ASN_MODULE_HEADERS+=INTEGER.h
ASN_MODULE_HEADERS+=NativeEnumerated.h
ASN_MODULE_SOURCES+=INTEGER.c
ASN_MODULE_HEADERS+=NULL.h
ASN_MODULE_SOURCES+=NULL.c
ASN_MODULE_SOURCES+=NativeEnumerated.c
ASN_MODULE_HEADERS+=NativeInteger.h
ASN_MODULE_SOURCES+=NativeInteger.c
ASN_MODULE_HEADERS+=asn_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=asn_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=asn_SET_OF.h
ASN_MODULE_SOURCES+=asn_SET_OF.c
ASN_MODULE_HEADERS+=constr_CHOICE.h
ASN_MODULE_SOURCES+=constr_CHOICE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE.h
ASN_MODULE_SOURCES+=constr_SEQUENCE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=constr_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=constr_SET_OF.h
ASN_MODULE_SOURCES+=constr_SET_OF.c
ASN_MODULE_HEADERS+=asn_application.h
ASN_MODULE_HEADERS+=asn_system.h
ASN_MODULE_HEADERS+=asn_codecs.h
ASN_MODULE_HEADERS+=asn_internal.h
ASN_MODULE_HEADERS+=OCTET_STRING.h
ASN_MODULE_SOURCES+=OCTET_STRING.c
ASN_MODULE_HEADERS+=BIT_STRING.h
ASN_MODULE_SOURCES+=BIT_STRING.c
ASN_MODULE_SOURCES+=asn_codecs_prim.c
ASN_MODULE_HEADERS+=asn_codecs_prim.h
ASN_MODULE_HEADERS+=ber_tlv_length.h
ASN_MODULE_SOURCES+=ber_tlv_length.c
ASN_MODULE_HEADERS+=ber_tlv_tag.h
ASN_MODULE_SOURCES+=ber_tlv_tag.c
ASN_MODULE_HEADERS+=ber_decoder.h
ASN_MODULE_SOURCES+=ber_decoder.c
ASN_MODULE_HEADERS+=der_encoder.h
ASN_MODULE_SOURCES+=der_encoder.c
ASN_MODULE_HEADERS+=constr_TYPE.h
ASN_MODULE_SOURCES+=constr_TYPE.c
ASN_MODULE_HEADERS+=constraints.h
ASN_MODULE_SOURCES+=constraints.c
ASN_MODULE_HEADERS+=xer_support.h
ASN_MODULE_SOURCES+=xer_support.c
ASN_MODULE_HEADERS+=xer_decoder.h
ASN_MODULE_SOURCES+=xer_decoder.c
ASN_MODULE_HEADERS+=xer_encoder.h
ASN_MODULE_SOURCES+=xer_encoder.c
ASN_MODULE_HEADERS+=per_support.h
ASN_MODULE_SOURCES+=per_support.c
ASN_MODULE_HEADERS+=per_decoder.h
ASN_MODULE_SOURCES+=per_decoder.c
ASN_MODULE_HEADERS+=per_encoder.h
ASN_MODULE_SOURCES+=per_encoder.c
ASN_MODULE_HEADERS+=per_opentype.h
ASN_MODULE_SOURCES+=per_opentype.c
ASN_CONVERTER_SOURCES+=converter-sample.c


lib_LTLIBRARIES=libsomething.la
libsomething_la_SOURCES=$(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)

# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
TARGET = progname
CFLAGS += -I.
OBJS=${ASN_MODULE_SOURCES:.c=.o} ${ASN_CONVERTER_SOURCES:.c=.o}

all: $(TARGET)

$(TARGET): ${OBJS}
	$(CC) $(CFLAGS) -o $(TARGET) ${OBJS} $(LDFLAGS) $(LIBS)
	
.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(TARGET)
	rm -f $(OBJS)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	asn1c -gen-PER -fincludes-quoted Common2.asn

