/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_RectangularRegion_H_
#define	_RectangularRegion_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TwoDLocation.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RectangularRegion */
typedef struct RectangularRegion {
	TwoDLocation_t	 northWest;
	TwoDLocation_t	 southEast;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RectangularRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RectangularRegion;

#ifdef __cplusplus
}
#endif

#endif	/* _RectangularRegion_H_ */
#include "asn_internal.h"
