/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_SequenceOfOctetString_H_
#define	_SequenceOfOctetString_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceOfOctetString */
typedef struct SequenceOfOctetString {
	A_SEQUENCE_OF(OCTET_STRING_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfOctetString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfOctetString;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfOctetString_H_ */
#include "asn_internal.h"
