/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_SequenceOfTimeStartAndEnd_H_
#define	_SequenceOfTimeStartAndEnd_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Time32.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceOfTimeStartAndEnd */
typedef struct SequenceOfTimeStartAndEnd {
	Time32_t	 startValidity;
	Time32_t	 endValidity;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfTimeStartAndEnd_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfTimeStartAndEnd;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfTimeStartAndEnd_H_ */
#include "asn_internal.h"
