/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_SequenceOfitsAidList_H_
#define	_SequenceOfitsAidList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ItsAid.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceOfitsAidList */
typedef struct SequenceOfitsAidList {
	A_SEQUENCE_OF(ItsAid_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfitsAidList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfitsAidList;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfitsAidList_H_ */
#include "asn_internal.h"
