/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_SignerInfo_H_
#define	_SignerInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "HashedId8.h"
#include "CertificateDigestWithOtherAlgorithm.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SignerInfo_PR {
	SignerInfo_PR_NOTHING,	/* No components present */
	SignerInfo_PR_self,
	SignerInfo_PR_certificateDigestWithSM3,
	SignerInfo_PR_certificate,
	SignerInfo_PR_certificateChain,
	SignerInfo_PR_certificateDigestWithOtherAlgorithm,
	/* Extensions may appear below */
	
} SignerInfo_PR;

/* Forward declarations */
struct Certificate;
struct SequenceOfCertificate;

/* SignerInfo */
typedef struct SignerInfo {
	SignerInfo_PR present;
	union SignerInfo_u {
		NULL_t	 self;
		HashedId8_t	 certificateDigestWithSM3;
		struct Certificate	*certificate;
		struct SequenceOfCertificate	*certificateChain;
		CertificateDigestWithOtherAlgorithm_t	 certificateDigestWithOtherAlgorithm;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignerInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignerInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Certificate.h"
#include "SequenceOfCertificate.h"

#endif	/* _SignerInfo_H_ */
#include "asn_internal.h"
