/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#include "SignerInfo.h"

static asn_per_constraints_t asn_PER_type_SignerInfo_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_SignerInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SignerInfo, choice.self),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"self"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignerInfo, choice.certificateDigestWithSM3),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashedId8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"certificateDigestWithSM3"
		},
	{ ATF_POINTER, 0, offsetof(struct SignerInfo, choice.certificate),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Certificate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"certificate"
		},
	{ ATF_POINTER, 0, offsetof(struct SignerInfo, choice.certificateChain),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SequenceOfCertificate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"certificateChain"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignerInfo, choice.certificateDigestWithOtherAlgorithm),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CertificateDigestWithOtherAlgorithm,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"certificateDigestWithOtherAlgorithm"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SignerInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* self */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* certificateDigestWithSM3 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* certificate */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* certificateChain */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* certificateDigestWithOtherAlgorithm */
};
static asn_CHOICE_specifics_t asn_SPC_SignerInfo_specs_1 = {
	sizeof(struct SignerInfo),
	offsetof(struct SignerInfo, _asn_ctx),
	offsetof(struct SignerInfo, present),
	sizeof(((struct SignerInfo *)0)->present),
	asn_MAP_SignerInfo_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SignerInfo = {
	"SignerInfo",
	"SignerInfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_SignerInfo_constr_1,
	asn_MBR_SignerInfo_1,
	5,	/* Elements count */
	&asn_SPC_SignerInfo_specs_1	/* Additional specs */
};

