/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_SubjectAttribute_H_
#define	_SubjectAttribute_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SubjectAssurance.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PublicKey;
struct SequenceOfitsAidList;
struct SequenceOfitsAidSspList;

/* SubjectAttribute */
typedef struct SubjectAttribute {
	struct PublicKey	*verificationKey	/* OPTIONAL */;
	struct PublicKey	*encryptionKey	/* OPTIONAL */;
	SubjectAssurance_t	*assuranceLevel	/* OPTIONAL */;
	struct SequenceOfitsAidList	*itsAidList	/* OPTIONAL */;
	struct SequenceOfitsAidSspList	*itsAidSspList	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubjectAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubjectAttribute;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PublicKey.h"
#include "SequenceOfitsAidList.h"
#include "SequenceOfitsAidSspList.h"

#endif	/* _SubjectAttribute_H_ */
#include "asn_internal.h"
