/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#include "ToBeSignedCrl.h"

static asn_TYPE_member_t asn_MBR_ToBeSignedCrl_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCrl, type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CrlType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCrl, caId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HashedId8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"caId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCrl, crlSerial),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Uint32,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"crlSerial"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCrl, startPeriod),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time32,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"startPeriod"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCrl, issueDate),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time32,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"issueDate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ToBeSignedCrl, nextCrl),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time32,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nextCrl"
		},
};
static const ber_tlv_tag_t asn_DEF_ToBeSignedCrl_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ToBeSignedCrl_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* caId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* crlSerial */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* startPeriod */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* issueDate */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* nextCrl */
};
static asn_SEQUENCE_specifics_t asn_SPC_ToBeSignedCrl_specs_1 = {
	sizeof(struct ToBeSignedCrl),
	offsetof(struct ToBeSignedCrl, _asn_ctx),
	asn_MAP_ToBeSignedCrl_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ToBeSignedCrl = {
	"ToBeSignedCrl",
	"ToBeSignedCrl",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ToBeSignedCrl_tags_1,
	sizeof(asn_DEF_ToBeSignedCrl_tags_1)
		/sizeof(asn_DEF_ToBeSignedCrl_tags_1[0]), /* 1 */
	asn_DEF_ToBeSignedCrl_tags_1,	/* Same as above */
	sizeof(asn_DEF_ToBeSignedCrl_tags_1)
		/sizeof(asn_DEF_ToBeSignedCrl_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ToBeSignedCrl_1,
	6,	/* Elements count */
	&asn_SPC_ToBeSignedCrl_specs_1	/* Additional specs */
};

