/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_ToBeSignedCrl_H_
#define	_ToBeSignedCrl_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CrlType.h"
#include "HashedId8.h"
#include "Uint32.h"
#include "Time32.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ToBeSignedCrl */
typedef struct ToBeSignedCrl {
	CrlType_t	 type;
	HashedId8_t	 caId;
	Uint32_t	 crlSerial;
	Time32_t	 startPeriod;
	Time32_t	 issueDate;
	Time32_t	 nextCrl;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ToBeSignedCrl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ToBeSignedCrl;

#ifdef __cplusplus
}
#endif

#endif	/* _ToBeSignedCrl_H_ */
#include "asn_internal.h"
