/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_ValidityRestriction_H_
#define	_ValidityRestriction_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Time32.h"
#include "SequenceOfTimeStartAndEnd.h"
#include "SequenceOfTimestartAndDuration.h"
#include "GeographicRegion.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ValidityRestriction_PR {
	ValidityRestriction_PR_NOTHING,	/* No components present */
	ValidityRestriction_PR_timeEnd,
	ValidityRestriction_PR_timeStartAndEnd,
	ValidityRestriction_PR_timestartAndDuration,
	ValidityRestriction_PR_region,
	/* Extensions may appear below */
	
} ValidityRestriction_PR;

/* ValidityRestriction */
typedef struct ValidityRestriction {
	ValidityRestriction_PR present;
	union ValidityRestriction_u {
		Time32_t	 timeEnd;
		SequenceOfTimeStartAndEnd_t	 timeStartAndEnd;
		SequenceOfTimestartAndDuration_t	 timestartAndDuration;
		GeographicRegion_t	 region;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ValidityRestriction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ValidityRestriction;

#ifdef __cplusplus
}
#endif

#endif	/* _ValidityRestriction_H_ */
#include "asn_internal.h"
