/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common2.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#include "GeographicRegion.h"

static asn_per_constraints_t asn_PER_type_GeographicRegion_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_GeographicRegion_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GeographicRegion, choice.circularRegion),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CircularRegion,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"circularRegion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeographicRegion, choice.rectangularRegion),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SequenceOfRectangularRegion,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rectangularRegion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GeographicRegion, choice.polygonalRegion),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PolygonalRegion,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"polygonalRegion"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_GeographicRegion_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* circularRegion */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rectangularRegion */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* polygonalRegion */
};
static asn_CHOICE_specifics_t asn_SPC_GeographicRegion_specs_1 = {
	sizeof(struct GeographicRegion),
	offsetof(struct GeographicRegion, _asn_ctx),
	offsetof(struct GeographicRegion, present),
	sizeof(((struct GeographicRegion *)0)->present),
	asn_MAP_GeographicRegion_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_GeographicRegion = {
	"GeographicRegion",
	"GeographicRegion",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_GeographicRegion_constr_1,
	asn_MBR_GeographicRegion_1,
	3,	/* Elements count */
	&asn_SPC_GeographicRegion_specs_1	/* Additional specs */
};

