/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_Certificate_H_
#define	_Certificate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint8.h"
#include "SubjectInfo.h"
#include "SubjectAttribute.h"
#include "ValidityRestriction.h"
#include "Signature.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignerInfo;

/* Certificate */
typedef struct Certificate {
	Uint8_t	 version;
	struct SignerInfo	*signerInfo;
	SubjectInfo_t	 subjectInfo;
	SubjectAttribute_t	 subjectAttributes;
	ValidityRestriction_t	 validityRestrictions;
	Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Certificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Certificate;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignerInfo.h"

#endif	/* _Certificate_H_ */
#include "asn_internal.h"
