/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_SequenceOfUint3_H_
#define	_SequenceOfUint3_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint3.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceOfUint3 */
typedef struct SequenceOfUint3 {
	A_SEQUENCE_OF(Uint3_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfUint3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfUint3;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfUint3_H_ */
#include "asn_internal.h"
