/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Common"
 * 	found in "Common.asn"
 * 	`asn1c -gen-PER -fincludes-quoted`
 */

#ifndef	_Signature_H_
#define	_Signature_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Signature_PR {
	Signature_PR_NOTHING,	/* No components present */
	Signature_PR_signature
	/* Extensions may appear below */
	
} Signature_PR;

/* Signature */
typedef struct Signature {
	Signature_PR present;
	union Signature_u {
		OCTET_STRING_t	 signature;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Signature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Signature;
extern asn_CHOICE_specifics_t asn_SPC_Signature_specs_1;
extern asn_TYPE_member_t asn_MBR_Signature_1[1];
extern asn_per_constraints_t asn_PER_type_Signature_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Signature_H_ */
#include "asn_internal.h"
